#!/bin/bash

# Terminate already running bar instances
killall -q polybar
# If all your bars have ipc enabled, you can also use 
# polybar-msg cmd quit

# Launch Polybar, using default config location ~/.config/polybar/config
polybar -r status > /dev/null 2>&1 &
polybar -r taskmanager > /dev/null 2>&1 &

# echo "Polybar launched..."
